### ISSUE TITLE
missing test dependencies?

### ISSUE THREAD

**Issue by 0-wiz-0** [rrthomas/psutils#50]
I've tried packaging psutils 3 for pkgsrc and installed the packages listed in pyproject.toml. After installing psutils and running pytest, I see lots of errors like this:
```
______________________________________________________________ ERROR at setup of test_psbook[3] ______________________________________________________________
file /scratch/wip/psutils/work/psutils-3.0/tests/testutils.py, line 108
  def file_test(
E       fixture 'file_type' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, datafiles, doctest_namespace, monkeypatch, pytestconfig, record_property,
 record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
/scratch/wip/psutils/work/psutils-3.0/tests/testutils.py:108
```

I also have many with
```
E       fixture 'regenerate_input' not found
```

Which pypi modules provide these fixtures? Could you please add them as pyproject.toml dependencies?

I also see warnings about a couple missing files:
```
E       FileNotFoundError: [Errno 2] No such file or directory: '/scratch/wip/psutils/work/psutils-3.0/tests/test-files/extractres/sample/ISO-8859-1Encoding-expected.enc'
E       FileNotFoundError: [Errno 2] No such file or directory: '/scratch/wip/psutils/work/psutils-3.0/tests/test-files/includeres/sample/ISO-8859-1Encoding.enc'                                                            
```
(there is no `tests/test-files` directory in the tarball).

**Comment by rrthomas** [comment]
Apologies, that's an oversight in packaging. I'll fix it ASAP.

**Comment by rrthomas** [comment]
Fixed in 3.0.1, which is now also on PyPI (`pspdfutils`). Thanks for the report.

**Comment by 0-wiz-0** [comment]
Ah, thanks for the hint. When I add that file manually to the 3.0.1 sources, I only have two errors remaining, those about the two missing test data files.

**Comment by rrthomas** [comment]
Should be fixed now in 3.0.3, do let me know if not!
